[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

healthcheckPath = "/healthz"
healthcheckTimeout = 30

[[services]]
name = "orchestralay"
